# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/MastersProgram/ECE6740/Labs/Lab2/Axi_Interface_Seq_Sqrt/Axi_Interface_Seq_Sqrt.srcs/sources_1/bd/axi_sqrt_bd/ip/axi_sqrt_bd_mypi_seqdeta_top_0_0/axi_sqrt_bd_mypi_seqdeta_top_0_0.xci
# IP: The module: 'axi_sqrt_bd_mypi_seqdeta_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/Axi_Interface_Seq_Sqrt/Axi_Interface_Seq_Sqrt.gen/sources_1/bd/axi_sqrt_bd/ip/axi_sqrt_bd_mypi_seqdeta_top_0_0/src/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_sqrt_bd_mypi_seqdeta_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/MastersProgram/ECE6740/Labs/Lab2/Axi_Interface_Seq_Sqrt/Axi_Interface_Seq_Sqrt.srcs/sources_1/bd/axi_sqrt_bd/ip/axi_sqrt_bd_mypi_seqdeta_top_0_0/axi_sqrt_bd_mypi_seqdeta_top_0_0.xci
# IP: The module: 'axi_sqrt_bd_mypi_seqdeta_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/Axi_Interface_Seq_Sqrt/Axi_Interface_Seq_Sqrt.gen/sources_1/bd/axi_sqrt_bd/ip/axi_sqrt_bd_mypi_seqdeta_top_0_0/src/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_sqrt_bd_mypi_seqdeta_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
