# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_processing_system7_0_1/uart_bd_processing_system7_0_1.xci
# IP: The module: 'uart_bd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_processing_system7_0_1/uart_bd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_processing_system7_0_1/uart_bd_processing_system7_0_1.xci
# IP: The module: 'uart_bd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_processing_system7_0_1/uart_bd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
