# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
# IP: The module: 'design_1_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_xbar_4/design_1_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
# IP: The module: 'design_1_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_xbar_4/design_1_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
