# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartB/PL/Lab1_axi_Addr/Lab1_axi_Addr.srcs/sources_1/bd/axi_addr/ip/axi_addr_c_addsub_0_0/axi_addr_c_addsub_0_0.xci
# IP: The module: 'axi_addr_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartB/PL/Lab1_axi_Addr/Lab1_axi_Addr.gen/sources_1/bd/axi_addr/ip/axi_addr_c_addsub_0_0/axi_addr_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_addr_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartB/PL/Lab1_axi_Addr/Lab1_axi_Addr.srcs/sources_1/bd/axi_addr/ip/axi_addr_c_addsub_0_0/axi_addr_c_addsub_0_0.xci
# IP: The module: 'axi_addr_c_addsub_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartB/PL/Lab1_axi_Addr/Lab1_axi_Addr.gen/sources_1/bd/axi_addr/ip/axi_addr_c_addsub_0_0/axi_addr_c_addsub_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_addr_c_addsub_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
