# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/ECE6740/zybo_master/PYNQ-Z1_C.xdc

# Block Designs: bd/uart_bd/uart_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_bd || ORIG_REF_NAME==uart_bd} -quiet] -quiet

# IP: bd/uart_bd/ip/uart_bd_processing_system7_0_0/uart_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_bd_processing_system7_0_0 || ORIG_REF_NAME==uart_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart_bd/ip/uart_bd_ps7_0_axi_periph_0/uart_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==uart_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart_bd/ip/uart_bd_rst_ps7_0_100M_0/uart_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==uart_bd_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: f:/ECE6740/Labs/Lab1/Lab1.gen/sources_1/bd/uart_bd/uart_bd_ooc.xdc
