# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_auto_pc_0/uart_bd_auto_pc_0.xci
# IP: The module: 'uart_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_auto_pc_0/uart_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_auto_pc_0/uart_bd_auto_pc_0.xci
# IP: The module: 'uart_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_auto_pc_0/uart_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
