domain_path: F:\ECE6740\Labs\Lab1\PS\UARTPlat\export\UARTPlat\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
