# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/uart_bd_design_1_wrapper_0_0.xci
# IP: The module: 'uart_bd_design_1_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_c_addsub_0_0/design_1_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_0 || ORIG_REF_NAME==design_1_c_addsub_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_Lab1_AxiInterface_Ad_0_0/design_1_Lab1_AxiInterface_Ad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Lab1_AxiInterface_Ad_0_0 || ORIG_REF_NAME==design_1_Lab1_AxiInterface_Ad_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_design_1_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_ooc.xdc

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/uart_bd_design_1_wrapper_0_0.xci
# IP: The module: 'uart_bd_design_1_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_c_addsub_0_0/design_1_c_addsub_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_0 || ORIG_REF_NAME==design_1_c_addsub_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_Lab1_AxiInterface_Ad_0_0/design_1_Lab1_AxiInterface_Ad_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Lab1_AxiInterface_Ad_0_0 || ORIG_REF_NAME==design_1_Lab1_AxiInterface_Ad_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_design_1_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_design_1_wrapper_0_0/src/design_1_ooc.xdc
