# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/ECE6740/Labs/Lab1/PartB/PL/Lab1_b/Lab1_b.srcs/sources_1/bd/adder_bd/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0.xci
# IP: The module: 'adder_bd_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ece6740/labs/lab1/partb/pl/tmp_edit_project.gen/sources_1/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/ece6740/labs/lab1/partb/pl/tmp_edit_project.gen/sources_1/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/ece6740/labs/lab1/partb/pl/tmp_edit_project.gen/sources_1/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/ECE6740/Labs/Lab1/PartB/PL/Lab1_b/Lab1_b.srcs/sources_1/bd/adder_bd/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0.xci
# IP: The module: 'adder_bd_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ece6740/labs/lab1/partb/pl/tmp_edit_project.gen/sources_1/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/ece6740/labs/lab1/partb/pl/tmp_edit_project.gen/sources_1/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/ece6740/labs/lab1/partb/pl/tmp_edit_project.gen/sources_1/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_bd_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
