# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ECE6740/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab2_Axi_Int_seq_sqrt/Lab2_Axi_Int_seq_sqrt.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Axi_Int_seq_sqrt || ORIG_REF_NAME==Lab2_Axi_Int_seq_sqrt} -quiet] -quiet

# IP: bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Axi_Int_seq_sqrt_processing_system7_0_0 || ORIG_REF_NAME==Lab2_Axi_Int_seq_sqrt_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_ps7_0_axi_periph_0/Lab2_Axi_Int_seq_sqrt_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Axi_Int_seq_sqrt_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab2_Axi_Int_seq_sqrt_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_rst_ps7_0_100M_0/Lab2_Axi_Int_seq_sqrt_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Axi_Int_seq_sqrt_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab2_Axi_Int_seq_sqrt_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_0/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_0 || ORIG_REF_NAME==Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_0} -quiet] -quiet

# IP: bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_auto_pc_0/Lab2_Axi_Int_seq_sqrt_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Axi_Int_seq_sqrt_auto_pc_0 || ORIG_REF_NAME==Lab2_Axi_Int_seq_sqrt_auto_pc_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/Lab2_Axi_Int_seq_sqrt_ooc.xdc
