# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/ECE6740/zybo_master/PYNQ-Z1_C.xdc

# Block Designs: bd/adder_bd/adder_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd || ORIG_REF_NAME==adder_bd} -quiet] -quiet

# IP: bd/adder_bd/ip/adder_bd_c_addsub_0_0/adder_bd_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_c_addsub_0_0 || ORIG_REF_NAME==adder_bd_c_addsub_0_0} -quiet] -quiet

# IP: bd/adder_bd/ip/adder_bd_clk_wiz_0/adder_bd_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_clk_wiz_0 || ORIG_REF_NAME==adder_bd_clk_wiz_0} -quiet] -quiet

# IP: bd/adder_bd/ip/adder_bd_lab1_axi_interface_0_0/adder_bd_lab1_axi_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_lab1_axi_interface_0_0 || ORIG_REF_NAME==adder_bd_lab1_axi_interface_0_0} -quiet] -quiet

# IP: bd/adder_bd/ip/adder_bd_xlslice_0_1/adder_bd_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_xlslice_0_1 || ORIG_REF_NAME==adder_bd_xlslice_0_1} -quiet] -quiet

# XDC: f:/ECE6740/Labs/Lab1/PartB/PL/Lab1_b/Lab1_b.gen/sources_1/bd/adder_bd/adder_bd_ooc.xdc
