# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_7/design_1_axi_cdma_0_7.xci
# IP: The module: 'design_1_axi_cdma_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_cdma_0_7/design_1_axi_cdma_0_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_cdma_0_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_cdma_0_7/design_1_axi_cdma_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_cdma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_cdma_0_7/design_1_axi_cdma_0_7.xci
# IP: The module: 'design_1_axi_cdma_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_cdma_0_7/design_1_axi_cdma_0_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_cdma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/ECE6740/Labs/Lab3/Testing_fft/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_cdma_0_7/design_1_axi_cdma_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_cdma_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
