# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Lab1_AxiInterface_Ad_0_0/design_1_Lab1_AxiInterface_Ad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Lab1_AxiInterface_Ad_0_0 || ORIG_REF_NAME==design_1_Lab1_AxiInterface_Ad_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_addsub_0_0/design_1_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_c_addsub_0_0 || ORIG_REF_NAME==design_1_c_addsub_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartB/PL/NewInterfaceOnly/NewInterfaceOnly.gen/sources_1/bd/design_1/design_1_ooc.xdc
