# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.srcs/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0.xci
# IP: The module: 'Lab2_Axi_Int_seq_sqrt_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Axi_Int_seq_sqrt_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.srcs/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0.xci
# IP: The module: 'Lab2_Axi_Int_seq_sqrt_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0/Lab2_Axi_Int_seq_sqrt_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Axi_Int_seq_sqrt_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
