# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/uart_bd_Lab1_Axi_Addr_Combo_0_0.xci
# IP: The module: 'uart_bd_Lab1_Axi_Addr_Combo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_xlslice_0_0/axi_addr_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_xlslice_0_0 || ORIG_REF_NAME==axi_addr_xlslice_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_xlconstant_0_0/axi_addr_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_xlconstant_0_0 || ORIG_REF_NAME==axi_addr_xlconstant_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_clk_wiz_0 || ORIG_REF_NAME==axi_addr_clk_wiz_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_c_addsub_0_0/axi_addr_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_c_addsub_0_0 || ORIG_REF_NAME==axi_addr_c_addsub_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_Lab1_AxiInterface_Ad_0_0/axi_addr_Lab1_AxiInterface_Ad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_Lab1_AxiInterface_Ad_0_0 || ORIG_REF_NAME==axi_addr_Lab1_AxiInterface_Ad_0_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_addr_clk_wiz_0 || ORIG_REF_NAME==axi_addr_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_addr_clk_wiz_0 || ORIG_REF_NAME==axi_addr_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0_ooc.xdc

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_Lab1_Axi_Addr_Combo_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_ooc.xdc

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.srcs/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/uart_bd_Lab1_Axi_Addr_Combo_0_0.xci
# IP: The module: 'uart_bd_Lab1_Axi_Addr_Combo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_xlslice_0_0/axi_addr_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_xlslice_0_0 || ORIG_REF_NAME==axi_addr_xlslice_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_xlconstant_0_0/axi_addr_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_xlconstant_0_0 || ORIG_REF_NAME==axi_addr_xlconstant_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_clk_wiz_0 || ORIG_REF_NAME==axi_addr_clk_wiz_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_c_addsub_0_0/axi_addr_c_addsub_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_c_addsub_0_0 || ORIG_REF_NAME==axi_addr_c_addsub_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_Lab1_AxiInterface_Ad_0_0/axi_addr_Lab1_AxiInterface_Ad_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_addr_Lab1_AxiInterface_Ad_0_0 || ORIG_REF_NAME==axi_addr_Lab1_AxiInterface_Ad_0_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_addr_clk_wiz_0 || ORIG_REF_NAME==axi_addr_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_addr_clk_wiz_0 || ORIG_REF_NAME==axi_addr_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_clk_wiz_0/axi_addr_clk_wiz_0_ooc.xdc

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/PYNQ-Z1_C.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_bd_Lab1_Axi_Addr_Combo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab1/PartA/Lab1/Lab1.gen/sources_1/bd/uart_bd/ip/uart_bd_Lab1_Axi_Addr_Combo_0_0/src/axi_addr_ooc.xdc
