# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.srcs/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2.xci
# IP: The module: 'Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_mypi_axi_seq_sqrt_0_0/axi_sqrt_bd_mypi_axi_seq_sqrt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_sqrt_bd_mypi_axi_seq_sqrt_0_0 || ORIG_REF_NAME==axi_sqrt_bd_mypi_axi_seq_sqrt_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_mypi_seqdeta_top_0_0/axi_sqrt_bd_mypi_seqdeta_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0 || ORIG_REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_mypi_seqdeta_top_0_0/src/PYNQ-Z1_C.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0 || ORIG_REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.srcs/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2.xci
# IP: The module: 'Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_mypi_axi_seq_sqrt_0_0/axi_sqrt_bd_mypi_axi_seq_sqrt_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_sqrt_bd_mypi_axi_seq_sqrt_0_0 || ORIG_REF_NAME==axi_sqrt_bd_mypi_axi_seq_sqrt_0_0} -quiet] -quiet

# IP: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_mypi_seqdeta_top_0_0/axi_sqrt_bd_mypi_seqdeta_top_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0 || ORIG_REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0} -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_mypi_seqdeta_top_0_0/src/PYNQ-Z1_C.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0 || ORIG_REF_NAME==axi_sqrt_bd_mypi_seqdeta_top_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/MastersProgram/ECE6740/Labs/Lab2/PartB/PartB_Inter/PartB_Inter.gen/sources_1/bd/Lab2_Axi_Int_seq_sqrt/ip/Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2/src/axi_sqrt_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Axi_Int_seq_sqrt_mypi_axi_sqrt_bd_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
